server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.shopping.demos.web.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xmutdatabase?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ZYLzyl190
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

